CREATE DATABASE [Common]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Common', FILENAME = N'D:\SQLServer\MSSQL16.MSSQLSERVER\MSSQL\DATA\Common.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Common_log', FILENAME = N'D:\SQLServer\MSSQL16.MSSQLSERVER\MSSQL\Log\Common_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [Common] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Common] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Common] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Common] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Common] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Common] SET ARITHABORT OFF 
GO
ALTER DATABASE [Common] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Common] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Common] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Common] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Common] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Common] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Common] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Common] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Common] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Common] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Common] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Common] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Common] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Common] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Common] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Common] SET  READ_WRITE 
GO
ALTER DATABASE [Common] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Common] SET  MULTI_USER 
GO
ALTER DATABASE [Common] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Common] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Common] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Common]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Common]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Common] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
