USE common;
GO

SET NOCOUNT ON;

DELETE
FROM dbo.colors;

INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Indian Red','#CD5C5C',205, 92, 92);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Coral','#F08080',240, 128, 128);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Salmon','#FA8072',250, 128, 114);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Salmon','#E9967A',233, 150, 122);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Salmon','#FFA07A',255, 160, 122);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Crimson','#DC143C',220, 20, 60);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Red','#FF0000',255, 0, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Fire Brick','#B22222',178, 34, 34);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Red','#8B0000',139, 0, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Pink','#FFC0CB',255, 192, 203);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Pink','#FFB6C1',255, 182, 193);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Hot Pink','#FF69B4',255, 105, 180);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('DeepPink','#FF1493',255, 20, 147);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Violet Red','#C71585',199, 21, 133);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Pale Violet Red','#DB7093',219, 112, 147);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Salmon','#FFA07A',255, 160, 122);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Coral','#FF7F50',255, 127, 80);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Tomato','#FF6347',255, 99, 71);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Orange Red','#FF4500',255, 69, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Orange','#FF8C00',255, 140, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Orange','#FFA500',255, 165, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Gold','#FFD700',255, 215, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Yellow','#FFFF00',255, 255, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Yellow','#FFFFE0',255, 255, 224);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Lemon Chiffon','#FFFACD',255, 250, 205);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Goldenrod Yellow','#FAFAD2',250, 250, 210);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Papaya Whip','#FFEFD5',255, 239, 213);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Moccasin','#FFE4B5',255, 228, 181);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Peach Puff','#FFDAB9',255, 218, 185);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Pale Goldenrod','#EEE8AA',238, 232, 170);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Khaki','#F0E68C',240, 230, 140);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Khaki','#BDB76B',189, 183, 107);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Lavender','#E6E6FA',230, 230, 250);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Thistle','#D8BFD8',216, 191, 216);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Plum','#DDA0DD',221, 160, 221);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Violet','#EE82EE',238, 130, 238);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Fuchsia','#FF00FF',255, 0, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Magenta','#FF00FF',255, 0, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Orchid','#BA55D3',186, 85, 211);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Purple','#9370DB',147, 112, 219);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Rebecca Purple','#663399',102, 51, 153);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Blue Violet','#8A2BE2',138, 43, 226);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Violet','#9400D3',148, 0, 211);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Orchid','#9932CC',153, 50, 204);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Magenta','#8B008B',139, 0, 139);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Purple','#800080',128, 0, 128);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Indigo','#4B0082',75, 0, 130);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Slate Blue','#6A5ACD',106, 90, 205);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Slate Blue','#483D8B',72, 61, 139);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Slate Blue','#7B68EE',123, 104, 238);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Green Yellow','#ADFF2F',173, 255, 47);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Chartreuse','#7FFF00',127, 255, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('LawnGreen','#7CFC00',124, 252, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Lime','#00FF00',0, 255, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Lime Green','#32CD32',50, 205, 50);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Pale Green','#98FB98',152, 251, 152);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Green','#90EE90',144, 238, 144);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Spring Green','#00FA9A',0, 250, 154);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Spring Green','#00FF7F',0, 255, 127);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Sea Green','#3CB371',60, 179, 113);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Sea Green','#2E8B57',46, 139, 87);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Forest Green','#228B22',34, 139, 34);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Green','#008000',0, 128, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Green','#006400',0, 100, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Yellow Green','#9ACD32',154, 205, 50);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Olive Drab','#6B8E23',107, 142, 35);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Olive','#808000',128, 128, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Olive Green','#556B2F',85, 107, 47);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Aquamarine','#66CDAA',102, 205, 170);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Sea Green','#8FBC8B',143, 188, 139);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Sea Green','#20B2AA',32, 178, 170);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Cyan','#008B8B',0, 139, 139);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Teal','#008080',0, 128, 128);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Aqua','#00FFFF',0, 255, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Cyan','#00FFFF',0, 255, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Cyan','#E0FFFF',224, 255, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Pale Turquoise','#AFEEEE',175, 238, 238);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Aquamarine','#7FFFD4',127, 255, 212);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Turquoise','#40E0D0',64, 224, 208);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Turquoise','#48D1CC',72, 209, 204);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Turquoise','#00CED1',0, 206, 209);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Cadet Blue','#5F9EA0',95, 158, 160);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Steel Blue','#4682B4',70, 130, 180);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Steel Blue','#B0C4DE',176, 196, 222);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Powder Blue','#B0E0E6',176, 224, 230);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Blue','#ADD8E6',173, 216, 230);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Sky Blue','#87CEEB',135, 206, 235);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Sky Blue','#87CEFA',135, 206, 250);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Deep Sky Blue','#00BFFF',0, 191, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dodger Blue','#1E90FF',30, 144, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Cornflower Blue','#6495ED',100, 149, 237);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Slate Blue','#7B68EE',123, 104, 238);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Royal Blue','#4169E1',65, 105, 225);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Blue','#0000FF',0, 0, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Medium Blue','#0000CD',0, 0, 205);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Blue','#00008B',0, 0, 139);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Navy','#000080',0, 0, 128);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Midnight Blue','#191970',25, 25, 112);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Cornsilk','#FFF8DC',255, 248, 220);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Blanched Almond','#FFEBCD',255, 235, 205);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Bisque','#FFE4C4',255, 228, 196);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Navajo White','#FFDEAD',255, 222, 173);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Wheat','#F5DEB3',245, 222, 179);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Burly Wood','#DEB887',222, 184, 135);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Tan','#D2B48C',210, 180, 140);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('RosyBrown','#BC8F8F',188, 143, 143);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('SandyBrown','#F4A460',244, 164, 96);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Goldenrod','#DAA520',218, 165, 32);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Goldenrod','#B8860B',184, 134, 11);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Peru','#CD853F',205, 133, 63);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Chocolate','#D2691E',210, 105, 30);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Saddle Brown','#8B4513',139, 69, 19);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Sienna','#A0522D',160, 82, 45);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Brown','#A52A2A',165, 42, 42);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Maroon','#800000',128, 0, 0);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('White','#FFFFFF',255, 255, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Snow','#FFFAFA',255, 250, 250);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Honey Dew','#F0FFF0',240, 255, 240);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Mint Cream','#F5FFFA',245, 255, 250);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Azure','#F0FFFF',240, 255, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Alice Blue','#F0F8FF',240, 248, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Ghost White','#F8F8FF',248, 248, 255);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('WhiteSmoke','#F5F5F5',245, 245, 245);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('SeaShell','#FFF5EE',255, 245, 238);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Beige','#F5F5DC',245, 245, 220);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('OldLace','#FDF5E6',253, 245, 230);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('FloralWhite','#FFFAF0',255, 250, 240);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Ivory','#FFFFF0',255, 255, 240);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Antique White','#FAEBD7',250, 235, 215);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Linen','#FAF0E6',250, 240, 230);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Lavender Blush','#FFF0F5',255, 240, 245);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Misty Rose','#FFE4E1',255, 228, 225);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Gainsboro','#DCDCDC',220, 220, 220);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Gray','#D3D3D3',211, 211, 211);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Silver','#C0C0C0',192, 192, 192);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Gray','#A9A9A9',169, 169, 169);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Gray','#808080',128, 128, 128);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dim Gray','#696969',105, 105, 105);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Light Slate Gray','#778899',119, 136, 153);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Slate Gray','#708090',112, 128, 144);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Dark Slate Gray','#2F4F4F',47, 79, 79);
INSERT INTO dbo.colors(colorName,hex,rgb_red,rgb_green,rgb_blue)VALUES('Black','#000000',0, 0, 0);
